### ISSUE TITLE
JSON File as DB

### ISSUE THREAD

**Issue by robinsadeghpour** [Continious-Software-Engineering/review-service#22]
Eine JSON Datei anlegen um diese als Datenbank zu nutzen.
Einen Rechner/Ermittler implementieren der die JSON ausliest und parsed in Objekte.
Einen Rechner/Ermittler implementieren der CRUD Optionen zur Verfügung stellt.

**Comment by ajuerss** [comment]
- turned out  JSON File as DB does not suit well in our application
